# =============================================================================
# Laravel Deployment
# =============================================================================
# Deploys a Laravel application with zero-downtime deployment pattern.
#
# Required secrets:
#   DEPLOY_HOST     - Server hostname or IP
#   DEPLOY_USER     - SSH username
#   DEPLOY_SSH_KEY  - Private SSH key
#   DEPLOY_PATH     - Absolute path on server
#
# Usage:
#   1. Copy this file to .github/workflows/deploy.yml
#   2. Configure the secrets in your repo settings
#   3. Customize the PHP version and deployment commands
# =============================================================================

name: Deploy Laravel

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, json, bcmath, pdo_mysql
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Run tests
        run: php artisan test

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}

            # Enable maintenance mode
            php artisan down --retry=60

            # Pull latest changes
            git pull origin main

            # Install dependencies
            composer install --no-dev --optimize-autoloader --no-interaction

            # Run migrations
            php artisan migrate --force

            # Clear and cache config
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # Restart queue workers
            php artisan queue:restart

            # Disable maintenance mode
            php artisan up

            echo "Laravel deployment complete!"
